### ISSUE TITLE
How to configure Dockerrun.aws.json for multicontainer docker microservices app?

### ISSUE THREAD

**Issue by exztinct01** [awslabs/elastic-beanstalk-samples#58]
I have two microservices images, a Go Rest API and a React frontend which are both inside my AWS ECR. I'll be using Elastic Beanstalk. Now since I believe they're on same machine so I configured the React app to fetch data from the API on localhost:8080. Below are the Dockerfiles for both. They worked in my dev environment so I pushed them to my ECR.

Dockerfile for Golang Rest API

    FROM golang
    ADD . /go/src/vsts/project/gorestapi
    WORKDIR /go/src/vsts/project/gorestapi
    RUN go get github.com/golang/dep/cmd/dep
    RUN dep ensure
    RUN go install .
    ENTRYPOINT /go/bin/gorestapi
    EXPOSE 8080
Dockerfile for React Frontend App

    FROM node:8.4.0-alpine
    WORKDIR /usr/src/app
    ENV NPM_CONFIG_LOGLEVEL warn
    RUN npm i -g serve
    CMD serve -s build/app -p 3000
    EXPOSE 3000
    COPY package.json package-lock.json ./
    RUN npm install
    COPY . .
    RUN npm run build

Image name is `<accountId>.dkr.ecr.us-east-1.amazonaws.com/<frontendName>:latest` and `<accountId>.dkr.ecr.us-east-1.amazonaws.com/<apiName>:latest`

I don't know if volume still needs to be declared, or the mountpoints, all I know is I need to put there the version of the dockerrun json to v2 and the name, image and portsmapping in container Definition. Most of the samples are confusing enough since none of them shows an app from private repo and they have those volumes, mountpoints, links, that I don't really understand how to use. I tried the one below but it did not work

    {
        "AWSEBDockerrunVersion": 2,
        "containerDefinitions": [
            {
                "name": "imgName",
                "image": "<accountId>.dkr.ecr.<region>.amazonaws.com/<apiName>:latest",
                "memory": 128,
                "portMappings": [
                    {
                        "hostPort": 8080,
                        "containerPort": 8080
                    }
                ],
                "links": [
                    "frontend"
                ]
            },
            {
                "name": "frontend",
                "image": "<accountId>.dkr.ecr.<region>.amazonaws.com/<frontendName>:latest",
                "memory": 128,
                "portMappings": [
                    {
                        "hostPort": 3000,
                        "containerPort": 3000
                    }
                ]
            }
        ]
    }

**Comment by dankhen** [comment]
Hi,

According to the [Multicontainer Docker Configuration](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html) and [Using Images From a Private Repository](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.container.console.html#docker-images-private) topics, you're missing one hard requirement. To use a Docker image in a private repository hosted by an online registry,  you have to use the `authentication` parameter of the `Dockerrun.aws.json` file to add the information about the Amazon S3 bucket that contains the authentication file that contains information required to authenticate with the registry. These two topics show what you need to add to `Dockerrun.aws.json`, and how the authentication file looks like.

The volumes and mountPoints aren't technically hard requirements. Typically, though, you'd need some of them, to give apps in your containers access to app files stored on the host instance, or to let apps in your containers write log files to the host instance file system. So if your app (or a proxy server in the container, etc.) tries to read or write any instance files, then it might fail if you don't have the right mountPoints defined.

I'd love to know which samples you found to be confusing or incomplete, so that we can consider any necessary fixes.

Thanks,
Danny

**Comment by exztinct01** [comment]
From [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.container.console.html#docker-images-private)

> Using Images from an Amazon ECR Repository
You can store your custom Docker images in AWS with Amazon Elastic Container Registry (Amazon ECR). When you store your Docker images in Amazon ECR, Elastic Beanstalk automatically authenticates to the Amazon ECR registry with your environment's instance profile, so you don't need to generate an authentication file and upload it to Amazon Simple Storage Service (Amazon S3).

You do, however, need to provide your instances with permission to access the images in your Amazon ECR repository by adding permissions to your environment's instance profile. You can attach the AmazonEC2ContainerRegistryReadOnly managed policy to the instance profile to provide read-only access to all Amazon ECR repositories in your account, or grant access to single repository by using the following template to create a custom policy:

>

**Comment by dankhen** [comment]
Oh, I am sorry - I was quoting from the Private Repository section, and you're using Amazon ECR. Thanks for the correction. But what's missing / confusing in the document topic you are quoting from? It covers configuring the required policy for your instances in the ECR case. The rest of what you were asking about (regarding volumes and mount points) is covered in [Multicontainer Docker Configuration](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html).

**Comment by downspot** [comment]
Running into a similar problem myself. 

{
    "AWSEBDockerrunVersion": "2",
    "containerDefinitions": [
        {
            "name": "islandsound_vowpal_test",
            "image": "islandsound/vowpal_wabbit_test",
            "essential": true,
            "portMappings": [
                {
                    "hostPort": 26542,
                    "containerPort": 26542
                }
            ]
        }
    ]
}

Gives me "Invalid Dockerrun.aws.json version, abort deployment."

**Comment by mwunderl** [comment]
Hi downspot. AWSEBDockerrunVersion takes an integer value `2`, not a string `"2"`.

**Comment by dankhen** [comment]
Great! @mwunderl's comment should help with @downspot's issue.

@exztinct01, do you still need clarifications to the examples, or can I close the issue?

**Comment by downspot** [comment]
Found the problem, I wasn't using multi container within AWS.

**Comment by dankhen** [comment]
Got it. I believe this is also @exztinct01's problem, because, on further investigation, it looks like using an integer rather than a string for `AWSEBDockerrunVersion` as @mwunderl was suggesting is safer, but in this case doesn't result in an error and works correctly. So the Multicontainer vs. Single Container Docker should be the answer.
Closing the issue.

**Comment by bgreatfit** [comment]
I have an issue @dankhen  
ERROR   ECS Application sourcebundle validation error: AWSEBDockerrunVersion is missing.
My Dockerrun.aws.json:
{
    "AWSEBDockerrunVersion": 2,
    "containerDefinitions": [
        {
            "command": [
                ".entrypoint.sh"
            ],
            "essential": true,
            "image": "mikegreat/docker-django",
            "memory": 128,
            "mountPoints": [
                {
                    "containerPath": "/app",
                    "sourceVolume": "_App"
                },
                {
                    "containerPath": "/app/static",
                    "sourceVolume": "Static_Volume"
                }
            ],
            "name": "django"
        },
        {
            "essential": true,
            "image": "mysql:5.6",
            "memory": 128,
            "mountPoints": [
                {
                    "containerPath": "/var/lib/mysql",
                    "sourceVolume": "Mysql-Data"
                }
            ],
            "name": "mysql",
            "portMappings": [
                {
                    "containerPort": 3306,
                    "hostPort": 8306
                }
            ]
        },
        {
            "essential": true,
            "image": "mikegreat/docker-nginx",
            "memory": 128,
            "mountPoints": [
                {
                    "containerPath": "/app/static",
                    "sourceVolume": "Static_Volume"
                }
            ],
            "name": "nginx",
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 1337
                }
            ]
        },
        {
            "environment": [
                {
                    "name": "PMA_ARBITRARY",
                    "value": "1"
                }
            ],
            "essential": true,
            "image": "phpmyadmin/phpmyadmin",
            "memory": 128,
            "mountPoints": [
                {
                    "containerPath": "/session",
                    "sourceVolume": "Session"
                }
            ],
            "name": "phpmyadmin",
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 8082
                }
            ]
        }
    ],
    "family": "",
    "volumes": [
        {
            "host": {
                "sourcePath": "./app"
            },
            "name": "_App"
        },
        {
            "host": {
                "sourcePath": "static_volume"
            },
            "name": "Static_Volume"
        },
        {
            "host": {
                "sourcePath": "mysql-data"
            },
            "name": "Mysql-Data"
        },
        {
            "host": {
                "sourcePath": "/session"
            },
            "name": "Session"
        }
    ]
}

**Comment by dankhen** [comment]
@bgreatfit, I don't know why you're getting this particular error. The only thing I can see in your file that we don't have in our document is `"family": ""`, which doesn't sound related to this error.

Other than that, your file looks like our document example, so your issue isn't exactly a documentation issue. This would be a good question to ask on the [AWS Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86&start=0).

**Comment by bgreatfit** [comment]
@dankhem Thank you. I have been wondering what happened. No one has answered my questions and it's been 4days

**Comment by HugoLiconV** [comment]
I'm getting the same error. This is my Dockerrun.aws.json file:

```JSON
{
  "AWSEBDockerrunVersion": 2,
  "containerDefinitions": [
    {
      "environment": [
        {
          "name": "PRISMA_CONFIG",
          "value": "port: 4466\nmanagementApiSecret: *******************\ndatabases:\n  default:\n    connector: postgres\n    host: *************.com\n    database: ********\n    schema: public\n    user: ******\n    password: ********\n    rawAccess: true\n    port: '5432'\n    migrations: true\n    connectionLimit: 2\n"
        }
      ],
      "essential": true,
      "image": "prismagraphql/prisma:1.34",
      "memory": 512,
      "name": "prisma",
      "portMappings": [
        {
          "containerPort": 4466,
          "hostPort": 6666
        }
      ]
    }
  ],
  "family": "",
  "volumes": []
}
```

**Comment by lvidal1** [comment]
For anyone facing this issue using the `eb cli`, commit and push the new version of your `Dockerrun.aws.json` file to your repo. That will reflect the changes properly to cli and then you can run `eb deploy`.

**Comment by lexNwimue** [comment]
Having a similar problem. Here's my Dockerrun.aws.json file:
```json
{
  "AWSEBDockerrunVersion": "1",
  "containerDefinitions": [
    {
      "name": "nginx",
      "image": "<account_id>.dkr.ecr.us-east-1.amazonaws.com/<repo-name>:proxy",
      "essential": true,
      "memory": 128,
      "portMappings": [
        {
          "hostPort": 80,
          "containerPort": 80
        }
      ]
    },
    {
      "name": "users",
      "image": "<account_id>.dkr.ecr.us-east-1.amazonaws.com/<repo-name>:users",
      "essential": true,
      "memory": 128,
      "portMappings": [
        {
          "hostPort": 4001,
          "containerPort": 4001
        }
      ]
    },
    {
      "name": "deliveries",
      "image": "<account_id>.dkr.ecr.us-east-1.amazonaws.com/<repo-name>:deliveries",
      "essential": true,
      "memory": 128,
      "portMappings": [
        {
          "hostPort": 4002,
          "containerPort": 4002
        }
      ]
    },
    {
      "name": "notifications",
      "image": "<account_id>.dkr.ecr.us-east-1.amazonaws.com/<repo-name>:notifications",
      "essential": true,
      "memory": 128,
      "portMappings": [
        {
          "hostPort": 4003,
          "containerPort": 4003
        }
      ]
    }
  ]
}

```

It keeps saying:

```bash
 You must specify the 'Ports' key when you specify the 'Image' key in 'Dockerrun.aws.json'. The deployment failed.
```

I've been on it for days now. I'd appreciate any help
